- hosts: localhost
  vars:
  - create_db_schema: no
  - add_cron: no
  tasks:
  
  - name: Install MariaDB
    yum: name=mariadb-server state=present

  - name: Install MySQL-python
    yum: name=MySQL-python state=present

  - name: Setup MariaDB Service
    service: name=mariadb enabled=true state=started

  - name: Create a database
    mysql_db: name={{db_name}} state=present encoding=utf8

  - name: Create DB structure
    when: create_db_schema
    mysql_db: name={{db_name}} state=import target=/scripts/create_db.sql
     
  - name: Create DB user
    mysql_user: name={{db_user}} password={{db_password}} priv={{db_name}}.*:all state=present

  - name: Create a backup directory
    file: name=/backups state=directory owner=root group=root mode=700
      
  - name: Add backup cron job
    when: add_cron
    cron: user=root special_time=daily job=/scripts/backup_prod_db.sh && /scripts/restore_dev_db.sh
